import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Noto_Kufi_Arabic } from "next/font/google";

import "./globals.css";

const Notokufiarabic = Noto_Kufi_Arabic({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Notokufiarabic.className}>
        <ThemeProvider enableSystem={true} attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
